Topic: Topic
Topics: Topics
SourceCode: Source code
GitHub: GitHub
EntityRelationshipDiagram: Entity relationship diagram
Documentation: Documentation
Description: Description
Name: Name
BookPart: Book part
BookParts: Book parts
Part: Part
Parts: Parts
BookElements: Book elements
RecordEdited: Record edited
RecordAdded: Record added
Edit: Edit
DeleteAreYouSure: Are you sure you want to delete?
ConfirmPlease: Please confirm
Series: Series
Title: Title
Book: Book
Sections: Sections
Tags: Tags
BookSectionTypes: Book section types
Books: Books
Actions: Actions
Homepage: Home page
Logo: Logo
MenuButton: Menu button
Save: Save
Cancel: Cancel
Dele: Delete
Change: Change
Add: Add
NoData: No data
NothingToShow: Nothing to show
EmptyDataSet: Empty dataset
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
Users: Users
Email: E-mail
ResetPassword: Reset password
RestoreLogin: Restore login
Password: Password
Username: Username
SignOut: Sign out
SignIn: Sign in
Test: Test
Report: Report
EnterYourQuery: Enter your query
Home: Home
AppName: BookLib