SourceCode: Исходный код
GitHub: GitHub
EntityRelationshipDiagram: Диаграмма взаимосвязи сущностей
Documentation: Документация
Description: Описание
Name: Имя
BookPart: Часть книги
BookParts: Части книги
Part: Часть
Parts: Части
BookElements: Элементы книги
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Edit: Редактировать
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Series: Серия
Title: Название
Book: Книга
Sections: Разделы
Tags: Теги
BookSectionTypes: Типы разделов книги
Books: Книги
Actions: Действия
Homepage: Домашняя страница
Logo: Логотип
MenuButton: Кнопка меню
Save: Сохранить
Cancel: Отмена
Dele: Удалить
Change: Изменить
Add: Добавить
NoData: Нет данных
NothingToShow: Нечего показывать
EmptyDataSet: Пустой набор данных
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
Users: Пользователи
Email: E-mail
ResetPassword: Сбросить пароль
RestoreLogin: Восстановить вход
Password: Пароль
Username: Логин
SignOut: Выйти
SignIn: Войти
Test: Тест
Report: Отчет
EnterYourQuery: Введите ваш запрос
Home: Главная
AppName: Библиотека